services:

  api:
    build:
      context: .
      dockerfile: product-api/Dockerfile
    container_name: detailing-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/detaling
      SPRING_DATASOURCE_USERNAME: detaling
      SPRING_DATASOURCE_PASSWORD: detaling
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    volumes:
      - ./product-api/users.txt:/app/users.txt
